### ISSUE TITLE
Arrow of SOFTLOCK

### ISSUE THREAD

**Issue by Nardeem** [TodePond/Arroost#286] opened 2024-01-12 19:21 UTC
You can softlock forcing you to restart by trying to duplicate the colour arrow or the time arrow. PLEASE, either fix it or add a way to stop.

**Comment by mahdoosh1** [comment] 2024-01-14 07:13
duplicate of #276

**Comment by mahdoosh1** [comment] 2024-01-14 07:14
wait no

**Comment by mahdoosh1** [comment] 2024-01-14 07:15
duplicate of #254

**Closed** 2024-01-14 16:55 UTC
Labels: duplicate
